default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: community_app_development

test:
  <<: *default
  database: community_app_test

production:
  <<: *default
  database: community_app_production
  username: community_app
  password: <%= ENV["DATABASE_PASSWORD"] %>
